services:
  backend:
    build: .
    ports:
      - "9000:9000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: duperdockerdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: